// Code generated by go generate; DO NOT EDIT.
package test

import (
	"io"

	"github.com/icon-project/goloop/common/db"
	"github.com/icon-project/goloop/module"
)

type BlockManagerBase struct{}

func (_r *BlockManagerBase) GetBlockByHeight(height int64) (module.Block, error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) GetLastBlock() (module.Block, error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) GetBlock(id []byte) (module.Block, error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) WaitForBlock(height int64) (<-chan module.Block, error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) NewBlockDataFromReader(r io.Reader) (module.BlockData, error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) Propose(parentID []byte, votes module.CommitVoteSet, cb func(module.BlockCandidate, error)) (canceler module.Canceler, err error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) Import(r io.Reader, flags int, cb func(module.BlockCandidate, error)) (canceler module.Canceler, err error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) ImportBlock(blk module.BlockData, flags int, cb func(module.BlockCandidate, error)) (canceler module.Canceler, err error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) Commit(module.BlockCandidate) error {
	panic("not implemented")
}

func (_r *BlockManagerBase) Finalize(module.BlockCandidate) error {
	panic("not implemented")
}

func (_r *BlockManagerBase) GetTransactionInfo(id []byte) (module.TransactionInfo, error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) Term() {
	panic("not implemented")
}

func (_r *BlockManagerBase) WaitForTransaction(parentID []byte, cb func()) bool {
	panic("not implemented")
}

func (_r *BlockManagerBase) SendTransactionAndWait(txi interface{}) (tid []byte, rc <-chan interface{}, err error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) WaitTransactionResult(id []byte) (rc <-chan interface{}, err error) {
	panic("not implemented")
}

func (_r *BlockManagerBase) ExportBlocks(from int64, to int64, dst db.Database, on func(height int64) error) error {
	panic("not implemented")
}

func (_r *BlockManagerBase) ExportGenesis(blk module.Block, writer module.GenesisStorageWriter) error {
	panic("not implemented")
}

func (_r *BlockManagerBase) GetGenesisData() (module.Block, module.CommitVoteSet, error) {
	panic("not implemented")
}
