// Code generated by go generate; DO NOT EDIT.
package test

import "github.com/icon-project/goloop/module"

type CommitVoteSetBase struct{}

func (_r *CommitVoteSetBase) Verify(block module.BlockData, validators module.ValidatorList) error {
	panic("not implemented")
}

func (_r *CommitVoteSetBase) Bytes() []byte {
	panic("not implemented")
}

func (_r *CommitVoteSetBase) Hash() []byte {
	panic("not implemented")
}

func (_r *CommitVoteSetBase) Timestamp() int64 {
	panic("not implemented")
}
