// Code generated by go generate; DO NOT EDIT.
package test

import "time"

type RegulatorBase struct{}

func (_r *RegulatorBase) MaxTxCount() int {
	panic("not implemented")
}

func (_r *RegulatorBase) CommitTimeout() time.Duration {
	panic("not implemented")
}

func (_r *RegulatorBase) OnTxExecution(count int, ed time.Duration, fd time.Duration) {
	panic("not implemented")
}

func (_r *RegulatorBase) SetCommitTimeout(i time.Duration, d time.Duration) {
	panic("not implemented")
}
