// Code generated by go generate; DO NOT EDIT.
package test

import "github.com/icon-project/goloop/module"

type TransactionListBase struct{}

func (_r *TransactionListBase) Get(int) (module.Transaction, error) {
	panic("not implemented")
}

func (_r *TransactionListBase) Iterator() module.TransactionIterator {
	panic("not implemented")
}

func (_r *TransactionListBase) Hash() []byte {
	panic("not implemented")
}

func (_r *TransactionListBase) Equal(module.TransactionList) bool {
	panic("not implemented")
}

func (_r *TransactionListBase) Flush() error {
	panic("not implemented")
}
