// Code generated by go generate; DO NOT EDIT.
package test

import "github.com/icon-project/goloop/module"

type TransactionBase struct{}

func (_r *TransactionBase) Group() module.TransactionGroup {
	panic("not implemented")
}

func (_r *TransactionBase) ID() []byte {
	panic("not implemented")
}

func (_r *TransactionBase) From() module.Address {
	panic("not implemented")
}

func (_r *TransactionBase) Bytes() []byte {
	panic("not implemented")
}

func (_r *TransactionBase) Hash() []byte {
	panic("not implemented")
}

func (_r *TransactionBase) Verify() error {
	panic("not implemented")
}

func (_r *TransactionBase) Version() int {
	panic("not implemented")
}

func (_r *TransactionBase) ToJSON(version module.JSONVersion) (interface{}, error) {
	panic("not implemented")
}

func (_r *TransactionBase) ValidateNetwork(nid int) bool {
	panic("not implemented")
}
