// Code generated by go generate; DO NOT EDIT.
package test

import "github.com/icon-project/goloop/module"

type ValidatorListBase struct{}

func (_r *ValidatorListBase) Hash() []byte {
	panic("not implemented")
}

func (_r *ValidatorListBase) Bytes() []byte {
	panic("not implemented")
}

func (_r *ValidatorListBase) Flush() error {
	panic("not implemented")
}

func (_r *ValidatorListBase) IndexOf(module.Address) int {
	panic("not implemented")
}

func (_r *ValidatorListBase) Len() int {
	panic("not implemented")
}

func (_r *ValidatorListBase) Get(i int) (module.Validator, bool) {
	panic("not implemented")
}
