package i;

/**
 * Represent an exception which is generated by user's code but propagates to the AVM.
 */
public class UncaughtException extends AvmException {
    private static final long serialVersionUID = 1L;

    public UncaughtException(Throwable thrownByVmInUserSpace) {
        super(thrownByVmInUserSpace);
    }

    public UncaughtException(String messageThrownByUser, Throwable throwableWrapper) {
        // We have no good way to communicate this within the standard exception hierarchy so just pass the message.
        super(messageThrownByUser, throwableWrapper);
    }
}
