#!/bin/sh

GOLANG_VERSION=${GOLANG_VERSION:-1.16.7}
PYTHON_VERSION=${PYTHON_VERSION:-3.7.11}
ALPINE_VERSION=${ALPINE_VERSION:-3.14}
JAVA_VERSION=${JAVA_VERSION:-11.0.7}
ROCKSDB_VERSION=${ROCKSDB_VERSION:-v6.22.1}
