#!/bin/sh

GOLANG_VERSION=${GOLANG_VERSION:-1.20.10}
PYTHON_VERSION=${PYTHON_VERSION:-3.7.17}
ALPINE_VERSION=${ALPINE_VERSION:-3.17}
JAVA_VERSION=${JAVA_VERSION:-11.0.21}
ROCKSDB_VERSION=${ROCKSDB_VERSION:-v8.3.3}
