package foundation.icon.ee.test;

public class TBCTestScenarios {
    private static final int S = TBCProtocol.VAR_TYPE_STATIC;
    private static final int I = TBCProtocol.VAR_TYPE_INSTANCE;
    private static final int L = TBCProtocol.VAR_TYPE_LOCAL;

    public static TBCTestScenario newValueScenario(int type, byte[] a1, byte[] a2) {
        return new TBCTestScenario()
                .set(type, 0, "0")
                .call(a2)
                    .call(a1)
                        .expect(type, 0, "0")
                        .set(type, 0, "1")
                    .revert()
                    .call(a1)
                        .expect(type, 0, "0")
                        .set(type, 0, "2")
                    .ret()
                    .call(a1)
                        .expect(type, 0, "2")
                        .set(type, 0, "3")
                    .ret()
                .revert()
                .expect(type, 0, "0")
                .call(a2)
                    .call(a1)
                        .expect(type, 0, "0")
                        .set(type, 0, "4")
                    .revert()
                    .call(a1)
                        .expect(type, 0, "0")
                        .set(type, 0, "5")
                    .ret()
                    .call(a1)
                        .expect(type, 0, "5")
                        .set(type, 0, "6")
                    .ret()
                .ret()
                .expect(type, 0, "6");
    }

    public static TBCTestScenario newRefScenario(int type, byte[] a1, byte[] a2) {
        return new TBCTestScenario()
                .set(S, TBCProtocol.MAX_VAR-1, "s-1")
                .set(S, TBCProtocol.MAX_VAR-2, "s-2")
                .set(S, TBCProtocol.MAX_VAR-3, "s-3")
                .set(S, TBCProtocol.MAX_VAR-4, "s-4")
                .setRef(type, 0, S, TBCProtocol.MAX_VAR-1)
                .setRef(type, 1, S, TBCProtocol.MAX_VAR-2)
                .setRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                .call(a2)
                    .call(a1)
                        .expectRef(type, 0, S, TBCProtocol.MAX_VAR-1)
                        .expectRef(type, 1, S, TBCProtocol.MAX_VAR-2)
                        .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                        .set(S, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(type, 1, S, TBCProtocol.MAX_VAR-3)
                    .revert()
                    .call(a1)
                        .expectRef(type, 0, S, TBCProtocol.MAX_VAR-1)
                        .expectRef(type, 1, S, TBCProtocol.MAX_VAR-2)
                        .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                        .set(S, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(type, 1, S, TBCProtocol.MAX_VAR-3)
                    .ret()
                    .call(a1)
                        .expectRefNE(type, 0, S, TBCProtocol.MAX_VAR-1)
                        .expectRefNE(type, 1, S, TBCProtocol.MAX_VAR-2)
                        .expectRef(type, 1, S, TBCProtocol.MAX_VAR-3)
                        .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                        .setRef(type, 1, S, TBCProtocol.MAX_VAR-4)
                    .ret()
                .revert()
                .expectRef(type, 0, S, TBCProtocol.MAX_VAR-1)
                .expectRef(type, 1, S, TBCProtocol.MAX_VAR-2)
                .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                .call(a2)
                    .call(a1)
                        .expectRef(type, 0, S, TBCProtocol.MAX_VAR-1)
                        .expectRef(type, 1, S, TBCProtocol.MAX_VAR-2)
                        .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                        .set(S, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(type, 1, S, TBCProtocol.MAX_VAR-3)
                    .revert()
                    .call(a1)
                        .expectRef(type, 0, S, TBCProtocol.MAX_VAR-1)
                        .expectRef(type, 1, S, TBCProtocol.MAX_VAR-2)
                        .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                        .set(S, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(type, 1, S, TBCProtocol.MAX_VAR-3)
                    .ret()
                    .call(a1)
                        .expectRefNE(type, 0, S, TBCProtocol.MAX_VAR-1)
                        .expectRefNE(type, 1, S, TBCProtocol.MAX_VAR-2)
                        .expectRef(type, 1, S, TBCProtocol.MAX_VAR-3)
                        .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3)
                        .setRef(type, 1, S, TBCProtocol.MAX_VAR-4)
                    .ret()
                .ret()
                .expectRefNE(type, 0, S, TBCProtocol.MAX_VAR-1)
                .expectRefNE(type, 1, S, TBCProtocol.MAX_VAR-2)
                .expectRef(type, 1, S, TBCProtocol.MAX_VAR-4)
                .expectRef(type, 2, S, TBCProtocol.MAX_VAR-3);
    }

    public static TBCTestScenario newLocalRefScenario(int srcType, byte[] a1, byte[] a2) {
        return new TBCTestScenario()
                .set(srcType, TBCProtocol.MAX_VAR-1, "s-1")
                .set(srcType, TBCProtocol.MAX_VAR-2, "s-2")
                .set(srcType, TBCProtocol.MAX_VAR-3, "s-3")
                .set(srcType, TBCProtocol.MAX_VAR-4, "s-4")
                .setRef(L, 0, srcType, TBCProtocol.MAX_VAR-1)
                .setRef(L, 1, srcType, TBCProtocol.MAX_VAR-2)
                .setRef(L, 2, srcType, TBCProtocol.MAX_VAR-3)
                .call(a2)
                    .call(a1)
                        .set(srcType, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(srcType, TBCProtocol.MAX_VAR-2, srcType, TBCProtocol.MAX_VAR-4)
                    .revert()
                .revert()
                .expectRef(L, 0, srcType, TBCProtocol.MAX_VAR-1)
                .expectRef(L, 1, srcType, TBCProtocol.MAX_VAR-2)
                .expectRef(L, 2, srcType, TBCProtocol.MAX_VAR-3)
                .call(a2)
                    .call(a1)
                        .set(srcType, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(srcType, TBCProtocol.MAX_VAR-2, srcType, TBCProtocol.MAX_VAR-4)
                    .ret()
                .revert()
                .expectRef(L, 0, srcType, TBCProtocol.MAX_VAR-1)
                .expectRef(L, 1, srcType, TBCProtocol.MAX_VAR-2)
                .expectRef(L, 2, srcType, TBCProtocol.MAX_VAR-3)
                .call(a2)
                    .call(a1)
                        .set(srcType, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(srcType, TBCProtocol.MAX_VAR-2, srcType, TBCProtocol.MAX_VAR-4)
                    .revert()
                .ret()
                .expectRef(L, 0, srcType, TBCProtocol.MAX_VAR-1)
                .expectRef(L, 1, srcType, TBCProtocol.MAX_VAR-2)
                .expectRef(L, 2, srcType, TBCProtocol.MAX_VAR-3)
                .call(a2)
                    .call(a1)
                        .set(srcType, TBCProtocol.MAX_VAR-1, "s-1")
                        .setRef(srcType, TBCProtocol.MAX_VAR-2, srcType, TBCProtocol.MAX_VAR-4)
                    .ret()
                .ret()
                .expectRefNE(L, 0, srcType, TBCProtocol.MAX_VAR-1)
                .expectRefNE(L, 1, srcType, TBCProtocol.MAX_VAR-2)
                .expectRef(L, 2, srcType, TBCProtocol.MAX_VAR-3);
    }
}
